---
- type: replace
  path: /instance_groups/name=bosh/properties/director/local_dns?/enabled
  value: true

- type: replace
  path: /instance_groups/name=bosh/properties/director/local_dns/include_index?
  value: true
