name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create final bosh release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules and fetch tags
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git submodule update --init --recursive
      - name: Download BOSH CLI
        uses: docker://dpb587/gget
        with:
          args: --exec github.com/cloudfoundry/bosh-cli "bosh=bosh-cli-*-linux-amd64"
      - name: Install BOSH CLI
        run: |
          mkdir -p  $GITHUB_WORKSPACE/tmp/bin
          mv ./bosh $GITHUB_WORKSPACE/tmp/bin/
          echo "::add-path::$GITHUB_WORKSPACE/tmp/bin"
      - name: Create BOSH Release
        id: final_release
        run: |
          new_version="$( echo "${{ github.ref }}" | sed 's#refs/tags/v##' )"
          echo ::set-output name=new_version::"$new_version"

          mkdir -p tmp

          if [[ -e "docs/releases/v${version}.md" ]]; then
            sed '1{/^---$/!q;};1,/^---$/d' "docs/releases/v${version}.md" > tmp/release-body
            echo "" >> tmp/release-body
          fi

          export filename=./athens-${new_version}.tgz
          echo ::set-output name=filename::"$filename"

          bosh create-release --timestamp-version --force --tarball=$filename

          cd tmp

          (
            sha=$(shasum -a 256 "$filename" | awk '{print $1}')
            echo "**Artifacts (sha256)**"
            echo ""
            echo "| sha256 | file |"
            echo "| ------ | ---- |"
            echo "| \`$sha\` | [$filename](https://github.com/s4heid/athens-bosh-release/releases/download/${{ github.ref }}/$filename) |"
          ) >> ./release-body

          echo ::set-output name=release_body::"$( jq -rRs 'gsub("\r";"%0D")|gsub("\n";"%0A")' < ./release-body )"
      - name: Create private.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x ; cat > ./config/private.yml <<EOF
          ---
          blobstore:
            provider: s3
            options:
              access_key_id: $AWS_ACCESS_KEY_ID
              secret_access_key: $AWS_SECRET_ACCESS_KEY
          EOF
      - name: Finalize release
        run: |
          bosh finalize-release --sha2 --version="${{ steps.final_release.outputs.new_version }}" \
            ./athens-${{ steps.final_release.outputs.new_version }}.tgz

          if git diff --no-ext-diff --quiet --exit-code; then
            >&2 echo "No diff detected in git." ; exit 1
          fi

          git config --local user.email "s4heid@users.noreply.github.com"
          git config --local user.name "Sebastian Heid"
          git add -A releases .final_builds ; git commit -m "Final release ${{ steps.final_release.outputs.new_version }}"
      - name: Cleanup private.yml
        if: always()
        shell: bash
        run: |
          rm -f ./config/private.yml
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@master # https://github.com/actions/create-release/issues/38
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: athens/${{ steps.final_release.outputs.new_version }}
          body: ${{ steps.final_release.outputs.release_body }}
          draft: true
          prerelease: false
      - name: Upload GitHub Release Assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./athens-${{ steps.final_release.outputs.new_version }}.tgz
          asset_name: athens-${{ steps.final_release.outputs.new_version }}.tgz
          asset_content_type: application/gzip
