name: Blobs Upgrader

on:
  schedule:
    - cron: '* 23 * * *'
  push:
    branches:
    - master

jobs:
  upgrade:
    name: Upgrade bosh blobs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
        with:
          ref: master
      - name: Create private.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x ; cat > ./config/private.yml <<EOF
          ---
          blobstore:
            provider: s3
            options:
              access_key_id: $AWS_ACCESS_KEY_ID
              secret_access_key: $AWS_SECRET_ACCESS_KEY
          EOF
      - name: Upgrade bosh blobs
        uses: s4heid/bosh-blobs-upgrader-action@master
        env:
          GIT_NAME: "GitHub Action"
          GIT_EMAIL: "action@github.com"
          GIT_UPDATE_BRANCH: blobs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_VERSION: ${{ env.TAG_VERSION }}
        with:
          repository: .
      - name: Cleanup private.yml
        if: always()
        shell: bash
        run: |
          rm -f ./config/private.yml
      - name: Run tests against bosh on docker
        uses: s4heid/bosh-action@master
        with:
          script: ./ci/actions/test.sh
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: blobs
          force: true