name: Blobs Upgrader

on:
  schedule:
    - cron: '* 23 * * *'
  push:
    branches:
    - upgrader

jobs:
  upgrade:
    name: Upgrade Bosh blobs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Upgrade Bosh Blobs
        uses: s4heid/bosh-blobs-upgrader@dev
        with:
          repository: .
      # - name: Run tests against bosh on docker
      #   uses: s4heid/bosh-action@master
      #   with:
      #     script: ./ci/actions/test.sh
      # - name: Create final release, push and tag the commit
      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: true
