name: Blobs Upgrader

on:
  schedule:
    - cron: '20 0 * * *'

jobs:
  upgrade:
    name: Upgrade bosh blobs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Create private.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set +x ; cat > ./config/private.yml <<EOF
          ---
          blobstore:
            provider: s3
            options:
              access_key_id: $AWS_ACCESS_KEY_ID
              secret_access_key: $AWS_SECRET_ACCESS_KEY
          EOF
      - name: Upgrade bosh blobs
        uses: s4heid/bosh-blobs-upgrader-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: .
      - name: Create Update Summary
        id: summary
        run: |
          if git diff-index --quiet HEAD ; then
            echo "no changes in git detected" ; exit 0
          fi
          echo ::set-output name=pr_body::"This is an automated pull request with updates of bosh release dependencies."
      - name: Cleanup private.yml
        if: always()
        shell: bash
        run: |
          rm -f ./config/private.yml
      - name: Run tests against bosh on docker
        if: steps.summary.outputs.pr_body != ''
        uses: s4heid/bosh-action@master
        with:
          script: ./ci/actions/test.sh
      - name: Create Pull Request
        if: steps.summary.outputs.pr_body != ''
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update bosh blobs
          committer: Sebastian Heid <s4heid@users.noreply.github.com>
          author: Sebastian Heid <s4heid@users.noreply.github.com>
          title: 'Automated bosh blobs update'
          body: ${{ steps.summary.outputs.pr_body }}
          labels: dependencies
          reviewers: s4heid
          branch: blobs